### ISSUE TITLE
Service 'web' failed to build

### ISSUE THREAD

**Issue by numbermonkey** [DartLazer/WhoIsHomeUI#1]
sorry, im a little new at this but can follow guides :) BUT I get the following error durnig the docker-compose

Step 7/7 : RUN  pip install -r requirements.txt && apt update && apt install -y                                                                 net-tools     arp-scan
 ---> Running in d94362562ce8
Collecting Django<4.0,>=3.0
  Downloading Django-3.2.12-py3-none-any.whl (7.9 MB)
Collecting psycopg2-binary>=2.8
  Downloading psycopg2-binary-2.9.3.tar.gz (380 kB)
ERROR: Exception:
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/tarfile.py", line 2305, in utime
    os.utime(targetpath, (tarinfo.mtime, tarinfo.mtime))
PermissionError: [Errno 1] Operation not permitted

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/pip/_internal/cli/base_command.py", line 173, in _main
    status = self.run(options, args)
  File "/usr/local/lib/python3.10/site-packages/pip/_internal/cli/req_command.py", line 203, in wrapper
    return func(self, options, args)
  File "/usr/local/lib/python3.10/site-packages/pip/_internal/commands/install.py", line 315, in run
    requirement_set = resolver.resolve(
  File "/usr/local/lib/python3.10/site-packages/pip/_internal/resolution/resolvelib/resolver.py", line 94, in resolve
    result = self._result = resolver.resolve(
  File "/usr/local/lib/python3.10/site-packages/pip/_vendor/resolvelib/resolvers.py", line 472, in resolve
    state = resolution.resolve(requirements, max_rounds=max_rounds)
  File "/usr/local/lib/python3.10/site-packages/pip/_vendor/resolvelib/resolvers.py", line 341, in resolve
    self._add_to_criteria(self.state.criteria, r, parent=None)
  File "/usr/local/lib/python3.10/site-packages/pip/_vendor/resolvelib/resolvers.py", line 172, in _add_to_criteria
    if not criterion.candidates:
  File "/usr/local/lib/python3.10/site-packages/pip/_vendor/resolvelib/structs.py", line 151, in __bool__
    return bool(self._sequence)
  File "/usr/local/lib/python3.10/site-packages/pip/_internal/resolution/resolvelib/found_candidates.py", line 140, in __bool__
    return any(self)
  File "/usr/local/lib/python3.10/site-packages/pip/_internal/resolution/resolvelib/found_candidates.py", line 128, in <genexpr>
    return (c for c in iterator if id(c) not in self._incompatible_ids)
  File "/usr/local/lib/python3.10/site-packages/pip/_internal/resolution/resolvelib/found_candidates.py", line 32, in _iter_built
    candidate = func()
  File "/usr/local/lib/python3.10/site-packages/pip/_internal/resolution/resolvelib/factory.py", line 204, in _make_candidate_from_link
    self._link_candidate_cache[link] = LinkCandidate(
  File "/usr/local/lib/python3.10/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 295, in __init__
    super().__init__(
  File "/usr/local/lib/python3.10/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 156, in __init__
    self.dist = self._prepare()
  File "/usr/local/lib/python3.10/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 227, in _prepare
    dist = self._prepare_distribution()
  File "/usr/local/lib/python3.10/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 305, in _prepare_distribution
    return self._factory.preparer.prepare_linked_requirement(
  File "/usr/local/lib/python3.10/site-packages/pip/_internal/operations/prepare.py", line 508, in prepare_linked_requirement
    return self._prepare_linked_requirement(req, parallel_builds)
  File "/usr/local/lib/python3.10/site-packages/pip/_internal/operations/prepare.py", line 550, in _prepare_linked_requirement
    local_file = unpack_url(
  File "/usr/local/lib/python3.10/site-packages/pip/_internal/operations/prepare.py", line 249, in unpack_url
    unpack_file(file.path, location, file.content_type)
  File "/usr/local/lib/python3.10/site-packages/pip/_internal/utils/unpacking.py", line 256, in unpack_file
    untar_file(filename, location)
  File "/usr/local/lib/python3.10/site-packages/pip/_internal/utils/unpacking.py", line 230, in untar_file
    tar.utime(member, path)
  File "/usr/local/lib/python3.10/tarfile.py", line 2307, in utime
    raise ExtractError("could not change modification time") from e
tarfile.ExtractError: could not change modification time
WARNING: You are using pip version 21.2.4; however, version 22.0.3 is available.
You should consider upgrading via the '/usr/local/bin/python -m pip install --upgrade pip' command.
The command '/bin/sh -c pip install -r requirements.txt && apt update && apt install -y     net-tools     arp-scan' returned a non-zero code: 2
ERROR: Service 'web' failed to build : Build failed

**Comment by DartLazer** [comment]
It looks like you have some permission issues with your docker setup.

[https://dev.to/elalemanyo/how-to-install-docker-and-docker-compose-on-raspberry-pi-1mo](url)

If you continue up to and including step 6 in this tutorial. Does the hello world container work for you?

**Comment by numbermonkey** [comment]
running an rpi-clone on it at the moment but I'll check when its finished. I have other containers running on it. It's my 'lab' server so I've had lots of dockerised services on it in the past. Thanks for replying :)

**Comment by DartLazer** [comment]
No worries thanks for taking the time to try my little pet project! This is my first ever github issue I'm handling so I'm still quite excited.

**Comment by numbermonkey** [comment]
Hello from Docker!
This message shows that your installation appears to be working correctly.

Hmm, that seems OK.

**Comment by DartLazer** [comment]
Hmm someone else on Reddit is having the same issue. I have no problems running it on 2 raspberry pi's (1 RPI3 and 1 RPI4) and ubuntu.

If you try:
`sudo docker-compose up`

Does that solve your issues?

**Comment by numbermonkey** [comment]
yep. on stable buster with recent update/upgrade run. Trying the above cmd :) Thanks.

**Comment by DartLazer** [comment]
[](https://stackoverflow.com/questions/69295832/docker-on-raspberrypi-does-not-install-pyyaml)

If you look at the top answer here.
If you could change the first line in the Dockerfile to the following line:

`FROM python:3-buster`

According to the stackexchange post this should work.

**Comment by DartLazer** [comment]
> [https://stackoverflow.com/questions/69295832/docker-on-raspberrypi-does-not-install-pyyaml](url)
> 
> If you look at the top answer here. If you could change the first line in the **Dockerfile** to the following line:
> 
> `FROM python:3-buster`
> 
> According to the stackexchange post this should work.

@numbermonkey Did you by any chance have any time to try this out? If it works I'd like to include it in a new commit.
Thanks!

**Comment by numbermonkey** [comment]
hey. sorry. holy shit am I busy at work. anyway, i ended up rebuilding the pi with the latest bullseye release. followed same docker & docker-compose instructions and got the Hello World. I cloned your git and then changed the DockerFile as indicated but using bullseye, of course. docker-compose up -d ran with no issues. Im thinking I should have tried it without modifying anything but that paste is out of the tube now. Thanks for your patience :D
